[project]
name = "gpqa"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "logfire",
    "anthropic",
    "pydantic-evals",
    "datasets",
    "pandas",
    "tqdm",
    "httpx==0.27.2",
    "ruff>=0.14.10",
]
