[project]
name = "gpqa"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "logfire",
    "anthropic",
    "pydantic-evals",
    "datasets",
    "pandas",
    "tqdm",
]
